FROM python:3.11-slim

WORKDIR /app

RUN groupadd -r router && useradd -r -g router router

COPY app/router_requirements.txt .
RUN pip install --no-cache-dir -r router_requirements.txt

COPY app/router.py .

ENV BLUE_URL=http://app-blue:5000
ENV GREEN_URL=http://app-green:5000

EXPOSE 5001

USER router

CMD ["python", "router.py"]
