apiVersion: v1
kind: ConfigMap
metadata:
  name: devops-playground-config
  namespace: devops
  labels:
    app: devops-playground
data:
  APP_VERSION:     "1.0.0"
  FLASK_ENV:       "production"
  GUNICORN_WORKERS: "2"
  GUNICORN_THREADS: "4"
